---
kind: pipeline
type: docker
name: build-pr

clone:
  disable: true

steps:
  - name: clone
    image: plugins/git
    settings:
      recursive: true
      tags: true
  - name: build
    # https://github.com/drGrove/drone-kaniko/tree/v0.7.0
    image: drgrove/drone-kaniko@sha256:e3045421c3683e6baf5628b22ea0ee1cd7ae217f4de0e1bc53a0a1a20335b108
    depends_on: [ clone ]
    settings:
      reproducible: true
      username: hashbangdrone
      password:
        from_secret: dockerhub_ro_passphrase

trigger:
  event:
    - pull_request
---
kind: pipeline
type: docker
name: build-master

clone:
  disable: true

trigger:
  branch:
    - master
  event:
    - push

steps:
  - name: clone
    image: plugins/git
    settings:
      recursive: true
      tags: true
  - name: build
    # https://github.com/drGrove/drone-kaniko/tree/v0.7.0
    image: drgrove/drone-kaniko@sha256:e3045421c3683e6baf5628b22ea0ee1cd7ae217f4de0e1bc53a0a1a20335b108
    depends_on: [ clone ]
    settings:
      repo: hashbang/book
      reproducible: true
      username: hashbangbot
      password:
        from_secret: dockerhub_password
---
kind: signature
hmac: 720d2cca26760af37303f42d5d96f99fc70f56b905dad020b5c1e49a30dbc0ee

...
